### ISSUE TITLE
wpcli Makefile error in --title=${WORDPRESS_WEBSITE_TITLE}

### ISSUE THREAD

**Issue by jeffmlazo** [kassambara/wordpress-docker-compose#2]
Hi @kassambara ,

I'm using a Manjaro Linux - KDE Edition and I found an error when trying to run the `make autoinstall`. Please see below error. 

> ⚙️ Configuring Wordpress parameters...
wp core install \
        --url=http://localhost \
        --title=My Blog Renamed 1 \
        --admin_user=wordpress \
        --admin_password=wordpress \
        --admin_email=your-email@example.com
Error: Too many positional arguments: Blog Renamed 1
make: *** [/scripts/Makefile:5: configure] Error 1
make: *** [Makefile:16: autoinstall] Error 2

It seems that Makefile doesn't like spaces so I tried to add a **" "** with the variables from <br/>**--title=${WORDPRESS_WEBSITE_TITLE}** to **--title="${WORDPRESS_WEBSITE_TITLE}"**.

And it works so far but I'm not entirely sure if it's a good idea to enclose all variables in the Makefile with **" "**.

**Comment by The0mikkel** [comment]
This is also the case when trying to run it in debian.
I get around this with the following code: 
```bash
sed -i -e "s/\$(WORDPRESS_WEBSITE_TITLE)/\"\$(WORDPRESS_WEBSITE_TITLE)\"/" wpcli/Makefile
```

Edit:
I didn't see that a merge request for this issue have been sent in.

**Comment by zipzit** [comment]
Me too.  I'm ran this in a Centos Docker environment (VPS)... 

```
⚙️ Configuring Wordpress parameters...
wp core install \
        --url=http://localhost \
        --title=My Blog \
        --admin_user=wordpress \
        --admin_password=wordpress \
        --admin_email=your-email@example.com
Error: Too many positional arguments: Blog                       <--- oops.
make: *** [/scripts/Makefile:6: configure] Error 1
make: *** [autoinstall] Error 2

```

**Comment by LiamKarlMitchell** [comment]
Same still a problem on WSL2 Ubuntu.
